# Generated by Django 5.0.14 on 2026-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
